apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::034090766650:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-14T10:20:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2833"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 65dd40a6-65dd-11ea-bec9-0694470da39a
